### ISSUE TITLE
Consider removing date based tags

### ISSUE THREAD

**Issue by jooola** [libretime/icecast-docker#32]
Consider removing date based tags, and document how to pin a specific image using sha256sum.

This should simplify the amount of tags we push and propose to the public. If people don't want to use dynamic tags (except the date based tags, all the tags we provide are dynamic), they should probably pin the images using sha256sums.

So instead of `ghcr.io/libretime/icecast:2.4.4-20220919`, people would use `ghcr.io/libretime/icecast:2.4.4@sha256:56e6f265675f07a80c4164f48b2ed6f3d371aed78a334c666dd2eda0d97afc5e`.

This makes upgrading the images using renovate way simpler as well.

@paddatrapper What do you think about this ?

**Comment by paddatrapper** [comment]
Yeah, I think that is a good idea
