### ISSUE TITLE
Push aarch64 image

### ISSUE THREAD

**Issue by ErSoul** [libretime/icecast-docker#43]
It would be great if you could provide images for ARM. It seems that this is a task that can only be made with the appropiate permissions according to [this blog](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/)

I built an image on my ARM machine without any modifications to your alpine.dockerfile

**Comment by jooola** [comment]
@ErSoul I merged #61, let me know if you are having any issues.
