### ISSUE TITLE
Consider adding an alpine variant  

### ISSUE THREAD

**Issue by jooola** [libretime/icecast-docker#5]
Maybe we want to add an alpine variant to our builds.

**Comment by paddatrapper** [comment]
Potentially, not sure how much space saving it would give us

**Comment by jooola** [comment]
> Potentially, not sure how much space saving it would give us

This is mainly for users not running libretime, as libretime rely on `debian:bullseye-slim` anyway, so no space reduction here. 

I want to make this image usable by anyone, so providing an alpine variant might come handy.

**Comment by jooola** [comment]
Fixed by #6
